### ISSUE TITLE
File does not exist: icp-backend/booking-microservice/node_modules/ibm_db/installer/driverInstall.js

### ISSUE THREAD

**Issue by rj00553657** [IBM/icp-airways#9]
When I am trying to install and push the booking-microservice I am getting this error below error,
root@mycluster:~/icp-airways-master/icp-backend/booking-microservice# npm i

> ibm_db@2.5.1 install /root/icp-airways-master/icp-backend/booking-microservice/node_modules/ibm_db
> node installer/driverInstall.js

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '/root/icp-airways-master/icp-backend/booking-microservice/node_modules/ibm_db/installer/driverInstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN icp-backend@1.0.0 No description
npm WARN icp-backend@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"ppc64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.5.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-07T09_58_51_001Z-debug.log

I have downloaded the repo from https://github.com/IBM/icp-airways .
Here in error it showing that this file does not exist /root/icp-airways-master/icp-backend/booking-microservice/node_modules/ibm_db/installer/driverInstall.js
I checked it Git the file is not there.

so we are using another link updated link mention is issues by author 
https://github.com/SaifRehman/ICP-Airways.git
git clone https://github.com/SaifRehman/ICP-Airways.git

In this link most services are not there - https://github.com/SaifRehman/ICP-Airways.git
Like • Checkin Microservice,  Listing Microservice, email-microservice and many more.

**Comment by SaifRehman** [comment]
this repo is out dated
use this repo: https://github.com/SaifRehman/ICP-Airways

**Comment by SaifRehman** [comment]
also you should be using node:9.8.0.
checking and booking ms is merged as one
listing microservices is renamed to listing-mongo-microservice 
email microservice is now celery only
